-- Users Table
CREATE TABLE users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name TEXT NOT NULL,
  mobile_number TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  dob TEXT NOT NULL,
  password TEXT NOT NULL,
  mpin TEXT,
  balance REAL DEFAULT 0,
  role TEXT DEFAULT 'user',
  kyc_status TEXT DEFAULT 'pending', -- pending, approved, rejected
  referral_code TEXT UNIQUE,
  referred_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Transactions Table
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) NOT NULL,
  type TEXT NOT NULL, -- add_balance, recharge, commission
  amount REAL NOT NULL,
  description TEXT,
  operator TEXT,
  mobile TEXT,
  status TEXT DEFAULT 'pending', -- success, pending, failed
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Wallet Requests Table
CREATE TABLE wallet_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) NOT NULL,
  utr_number TEXT UNIQUE NOT NULL,
  amount REAL NOT NULL,
  payment_date TEXT NOT NULL,
  upi_id TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- KYC Submissions Table
CREATE TABLE kyc_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) NOT NULL,
  aadhaar_number TEXT NOT NULL,
  pan_number TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Settings Table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Support Requests Table
CREATE TABLE support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  email TEXT,
  mobile TEXT,
  type TEXT, -- password, mpin, support
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Recharge Plans Table
CREATE TABLE recharge_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator TEXT NOT NULL,
  amount REAL NOT NULL,
  validity TEXT,
  description TEXT,
  category TEXT, -- Topup, Data, Unlimited, etc.
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Commissions Table
CREATE TABLE commissions (
  operator TEXT PRIMARY KEY,
  percentage REAL DEFAULT 0,
  flat_amount REAL DEFAULT 0,
  type TEXT DEFAULT 'percentage' -- percentage, flat
);

-- Notifications Table
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id), -- NULL for broadcast
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Initialize Commissions
INSERT INTO commissions (operator, percentage) VALUES 
('Jio', 3.0),
('Airtel', 2.5),
('Vi', 3.5),
('BSNL', 4.0)
ON CONFLICT (operator) DO NOTHING;

-- Default Settings
INSERT INTO settings (key, value) VALUES ('logo_url', 'https://seeklogo.com/images/R/recharge-logo-7DA7D8A17F-seeklogo.com.png')
ON CONFLICT (key) DO NOTHING;

-- RPC: Increment Balance
CREATE OR REPLACE FUNCTION increment_balance(user_id UUID, amount_to_add REAL)
RETURNS void AS $$
BEGIN
  UPDATE users
  SET balance = balance + amount_to_add
  WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Decrement Balance
CREATE OR REPLACE FUNCTION decrement_balance(user_id UUID, amount_to_sub REAL)
RETURNS void AS $$
BEGIN
  UPDATE users
  SET balance = balance - amount_to_sub
  WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
